### ISSUE TITLE
Thắc mắc 

### ISSUE THREAD

**Issue by LiamVu** [bacsonvv/MyWalletProject#379]
Bạn có thể để lại mail mình thắc mắc 1 chút về code được không ạ ?

**Comment by bacsonvv** [comment]
> Bạn có thể để lại mail mình thắc mắc 1 chút về code được không ạ ?

Chào bạn, đây là một project nhóm trong quá trình mình thực tập ios tại công ty mình đang làm việc, code đã khá lâu và mình cũng không code toàn bộ project nên có thể sẽ không nắm được hết toàn bộ. Tuy nhiên mình sẽ rất vui nếu có thể giúp bạn
Gửi thắc mắc cho mình qua: bacsonvv@gmail.com
